feat: Archs - Add aarch64-unknown-linux-musl (untested)

diff --git a/.github/workflows/rust-cd.yaml b/.github/workflows/rust-cd.yaml
--- a/.github/workflows/rust-cd.yaml
+++ b/.github/workflows/rust-cd.yaml
@@ -8,7 +8,7 @@ on:
   workflow_dispatch: # Run with Run Workflow button in GitHub Action Job, set debug_enabled=true for interactive ssh session.
     inputs:
       debug_enabled:
-        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
+        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
         required: false
         default: false
 
@@ -48,7 +48,7 @@ jobs:
         run: |
           function ok() {
             echo -e "\e[1;32mOK\e[0m"
-          }  
+          }
           function err() {
             echo -e "\e[1;31m${@}\e[0m" >&2
             exit 1
@@ -57,7 +57,7 @@ jobs:
           CRATE_VERSION=$(cat Cargo.toml | grep -e "^version" | head -1 | cut -d '=' -f2 | sed -e "s/ //" -e "s/\"//g")
           [[ $GITHUB_REF == *"refs/tags"* ]] && TAG=$GITHUB_REF || err "Cannot determine git tag."
           TAG=${TAG/refs\/tags\//}
-          [ "$CRATE_VERSION" = "$TAG" ] && ok "OK" || err "ERROR: Crate version does not match the git (release) tag."  
+          [ "$CRATE_VERSION" = "$TAG" ] && ok "OK" || err "ERROR: Crate version does not match the git (release) tag."
 
   publish-to-github:
     name: Building ${{ matrix.job.target }}
@@ -71,6 +71,7 @@ jobs:
           - { os: ubuntu-latest , target: x86_64-unknown-linux-gnu,    use-cross: false }
           - { os: ubuntu-latest , target: x86_64-unknown-linux-musl,   use-cross: false }
           - { os: ubuntu-latest,  target: aarch64-unknown-linux-gnu,   use-cross: true }
+          - { os: ubuntu-latest,  target: aarch64-unknown-linux-musl,  use-cross: true }
           - { os: ubuntu-latest,  target: arm-unknown-linux-gnueabihf, use-cross: true }
           - { os: ubuntu-latest,  target: i686-unknown-linux-gnu,      use-cross: true }
 
@@ -84,7 +85,7 @@ jobs:
 
       - name: Install required dependencies
         env:
-          RUSTFLAGS: "-C target-feature=-crt-static" 
+          RUSTFLAGS: "-C target-feature=-crt-static"
         shell: bash
         run: |
           if [[ ${{ matrix.job.target }} == arm-unknown-linux-gnueabihf ]]; then
@@ -94,6 +95,10 @@ jobs:
           if [[ ${{ matrix.job.target }} == aarch64-unknown-linux-gnu ]]; then
               sudo apt update
               sudo apt-get install -y binutils-aarch64-linux-gnu
+          fi
+          if [[ ${{ matrix.job.target }} == aarch64-unknown-linux-musl ]]; then
+              sudo apt update
+              sudo apt-get install -y musl
           fi
           if [[ ${{ matrix.job.target }} == x86_64-unknown-linux-musl ]]; then
               rustup target add x86_64-unknown-linux-musl
@@ -140,7 +145,7 @@ jobs:
             ${{ inputs.PROJECT_NAME }}*.deb
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- 
+
   publish-to-dockerhub:
     name: Building dockers
     runs-on: ubuntu-latest
@@ -204,7 +209,7 @@ jobs:
           platforms: linux/amd64, linux/arm64
           push: true
           tags: ${{ steps.prep.outputs.tags }}
- 
+
   publish-to-cargo:
     name: Publishing to Cargo
     if: github.event_name == 'push'
